theme: jekyll-theme-minimal
title: Emily Barranca
description: I am an Assitant Professor of Mathematics at St. Mary's College of Maryland! I am the faculty advisor for Math Club and Gender and Sexuality Minorities in Computer Science. Outside of St. Mary's, I am a member of Spectra and the Association for Women in Mathematics
logo: /files/profile.jpg
